export const ticketListItems = [
    {
        id:1,
        ticketLabel: "Implementing DND",
        effortPoint: "9",
        ticketOwner: "Shally",
        status: "TODO",
        lastUpdated: new Date(2024, 6, 8),
    },
    {
        id:2,
        ticketLabel: "Fix login issue",
        effortPoint: "5",
        ticketOwner: "John",
        status: "IN_PROGRESS",
        lastUpdated: new Date(2024, 6, 9),
    },
    {
        id:3,
        ticketLabel: "Update user profile page",
        effortPoint: "7",
        ticketOwner: "Alice",
        status: "CODE_REVIEW",
        lastUpdated: new Date(2024, 6, 7),
    },
    {
        id:4,
        ticketLabel: "Optimize database queries",
        effortPoint: "8",
        ticketOwner: "Bob",
        status: "DONE",
        lastUpdated: new Date(2024, 6, 2),
    },
    {
        id:5,
        ticketLabel: "Design new homepage",
        effortPoint: "6",
        ticketOwner: "Jane",
        status: "TODO",
        lastUpdated: new Date(2024, 6, 4),
    },
    {
        id:6,
        ticketLabel: "Write unit tests",
        effortPoint: "4",
        ticketOwner: "Tom",
        status: "IN_PROGRESS",
        lastUpdated: new Date(2024, 6, 12),
    },
    {
        id:7,
        ticketLabel: "Refactor CSS",
        effortPoint: "3",
        ticketOwner: "Emma",
        status: "DONE",
        lastUpdated: new Date(2024, 6, 10),
    },
    {
        id:8,
        ticketLabel: "Create API documentation",
        effortPoint: "5",
        ticketOwner: "Lucas",
        status: "CODE_REVIEW",
        lastUpdated: new Date(2024, 6, 4),
    },
    {
        id:9,
        ticketLabel: "Setup CI/CD pipeline",
        effortPoint: "8",
        ticketOwner: "Sophia",
        status: "TODO",
        lastUpdated: new Date(2024, 6, 2),
    },
    {
        id:10,
        ticketLabel: "Resolve security vulnerabilities",
        effortPoint: "9",
        ticketOwner: "Mike",
        status: "IN_PROGRESS",
        lastUpdated: new Date(2024, 6, 1),
    },
    {
        id:11,
        ticketLabel: "Improve loading speed",
        effortPoint: "6",
        ticketOwner: "David",
        status: "CODE_REVIEW",
        lastUpdated: new Date(2024, 6, 5),
    },
    {
        id:12,
        ticketLabel: "Conduct user testing",
        effortPoint: "7",
        ticketOwner: "Ella",
        status: "DONE",
        lastUpdated: new Date(2024, 6, 6),
    }
];
